import type { Venue, VenueDressCode, VenuePriceRange } from './types'
import { normalizeVenueCategoryKey, venueCategoryLabel } from './venue-categories'

type CuratedInput = {
  id: string
  name: string
  lat: number
  lng: number
  address: string
  neighborhood: string
  categoryKey: string
  pulseScore: number
  phone?: string
  website?: string
  menuUrl?: string
  dressCode?: VenueDressCode
  coverChargeCents?: number | null
  coverChargeNote?: string
  priceRange?: VenuePriceRange
  indoorOutdoor?: Venue['indoorOutdoor']
  hours?: Venue['hours']
  accessibilityFeatures?: Venue['accessibilityFeatures']
}

function curated(row: CuratedInput): Venue {
  const categoryKey = normalizeVenueCategoryKey(row.categoryKey)
  return {
    id: row.id,
    name: row.name,
    location: { lat: row.lat, lng: row.lng, address: row.address },
    city: 'Seattle',
    state: 'WA',
    neighborhood: row.neighborhood,
    category: venueCategoryLabel(categoryKey),
    categoryKey,
    pulseScore: row.pulseScore,
    phone: row.phone,
    website: row.website,
    menuUrl: row.menuUrl ?? null,
    dressCode: row.dressCode ?? null,
    coverChargeCents: row.coverChargeCents ?? null,
    coverChargeNote: row.coverChargeNote ?? null,
    priceRange: row.priceRange ?? null,
    indoorOutdoor: row.indoorOutdoor ?? 'indoor',
    hours: row.hours,
    accessibilityFeatures: row.accessibilityFeatures,
    seeded: true,
    integrations: {
      maps: {
        googleMapsUrl: `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(row.name + ' ' + row.address)}`,
      },
    },
  }
}

const nightlifeHours = {
  thursday: '9:00 PM - 2:00 AM',
  friday: '9:00 PM - 3:00 AM',
  saturday: '9:00 PM - 3:00 AM',
} as const

const musicHours = {
  wednesday: '7:00 PM - 2:00 AM',
  thursday: '7:00 PM - 2:00 AM',
  friday: '7:00 PM - 2:00 AM',
  saturday: '7:00 PM - 2:00 AM',
} as const

/**
 * Seattle MVP curated nightlife inventory (PRD P0-4).
 * Target neighborhoods: Capitol Hill, Belltown, Ballard, Fremont, Downtown.
 */
export const SEATTLE_NIGHTLIFE_CURATED: Venue[] = [
  curated({
    id: 'sea-neumos',
    name: 'Neumos',
    lat: 47.6145,
    lng: -122.3205,
    address: '925 E Pike St, Seattle, WA',
    neighborhood: 'Capitol Hill',
    categoryKey: 'music_venue',
    pulseScore: 85,
    phone: '(206) 709-9442',
    website: 'https://neumos.com',
    dressCode: 'casual',
    coverChargeCents: 2000,
    coverChargeNote: 'Ticketed shows vary',
    priceRange: 2,
    hours: { ...musicHours, sunday: 'Closed', monday: 'Closed', tuesday: 'Closed' },
  }),
  curated({
    id: 'sea-barboza',
    name: 'Barboza',
    lat: 47.6145,
    lng: -122.3207,
    address: '925 E Pike St, Seattle, WA',
    neighborhood: 'Capitol Hill',
    categoryKey: 'nightclub',
    pulseScore: 78,
    dressCode: 'smart_casual',
    coverChargeCents: 1500,
    priceRange: 2,
    hours: { ...nightlifeHours },
  }),
  curated({
    id: 'sea-q-nightclub',
    name: 'Q Nightclub',
    lat: 47.6138,
    lng: -122.3198,
    address: '1426 Broadway, Seattle, WA',
    neighborhood: 'Capitol Hill',
    categoryKey: 'nightclub',
    pulseScore: 92,
    phone: '(206) 200-7074',
    website: 'https://qnightclub.com',
    dressCode: 'smart_casual',
    coverChargeCents: 2000,
    priceRange: 3,
    hours: {
      thursday: '9:00 PM - 3:00 AM',
      friday: '9:00 PM - 4:00 AM',
      saturday: '9:00 PM - 4:00 AM',
    },
  }),
  curated({
    id: 'sea-kremwerk',
    name: 'Kremwerk',
    lat: 47.6154,
    lng: -122.3213,
    address: '1809 Minor Ave, Seattle, WA',
    neighborhood: 'Capitol Hill',
    categoryKey: 'nightclub',
    pulseScore: 68,
    dressCode: 'casual',
    coverChargeCents: 1000,
    priceRange: 2,
    hours: { ...nightlifeHours },
  }),
  curated({
    id: 'sea-neighbourhood',
    name: 'Neighbourhood',
    lat: 47.6142,
    lng: -122.3189,
    address: '1509 E Madison St, Seattle, WA',
    neighborhood: 'Capitol Hill',
    categoryKey: 'bar',
    pulseScore: 64,
    dressCode: 'casual',
    coverChargeCents: 0,
    coverChargeNote: 'Usually free',
    priceRange: 2,
    hours: {
      monday: '4:00 PM - 2:00 AM',
      tuesday: '4:00 PM - 2:00 AM',
      wednesday: '4:00 PM - 2:00 AM',
      thursday: '4:00 PM - 2:00 AM',
      friday: '4:00 PM - 2:00 AM',
      saturday: '4:00 PM - 2:00 AM',
      sunday: '4:00 PM - 2:00 AM',
    },
  }),
  curated({
    id: 'sea-rhein-haus',
    name: 'Rhein Haus',
    lat: 47.6131,
    lng: -122.3165,
    address: '912 12th Ave, Seattle, WA',
    neighborhood: 'Capitol Hill',
    categoryKey: 'bar',
    pulseScore: 70,
    phone: '(206) 325-5409',
    website: 'https://rheinhausseattle.com',
    dressCode: 'casual',
    coverChargeCents: 0,
    priceRange: 2,
    hours: {
      monday: '4:00 PM - 12:00 AM',
      tuesday: '4:00 PM - 12:00 AM',
      wednesday: '4:00 PM - 12:00 AM',
      thursday: '4:00 PM - 1:00 AM',
      friday: '4:00 PM - 2:00 AM',
      saturday: '11:00 AM - 2:00 AM',
      sunday: '11:00 AM - 12:00 AM',
    },
  }),
  curated({
    id: 'sea-canon',
    name: 'Canon',
    lat: 47.614,
    lng: -122.3168,
    address: '928 12th Ave, Seattle, WA',
    neighborhood: 'Capitol Hill',
    categoryKey: 'cocktail_bar',
    pulseScore: 74,
    website: 'https://canonseattle.com',
    dressCode: 'smart_casual',
    coverChargeCents: 0,
    priceRange: 3,
    hours: {
      tuesday: '5:00 PM - 12:00 AM',
      wednesday: '5:00 PM - 12:00 AM',
      thursday: '5:00 PM - 1:00 AM',
      friday: '5:00 PM - 2:00 AM',
      saturday: '5:00 PM - 2:00 AM',
    },
  }),
  curated({
    id: 'sea-crocodile',
    name: 'The Crocodile',
    lat: 47.6162,
    lng: -122.3488,
    address: '2200 2nd Ave, Seattle, WA',
    neighborhood: 'Belltown',
    categoryKey: 'music_venue',
    pulseScore: 72,
    phone: '(206) 441-4618',
    website: 'https://thecrocodile.com',
    dressCode: 'casual',
    coverChargeCents: 2500,
    coverChargeNote: 'Show dependent',
    priceRange: 2,
    hours: { ...musicHours, monday: 'Closed', sunday: 'Closed' },
  }),
  curated({
    id: 'sea-rumpus-room',
    name: 'Rumpus Room',
    lat: 47.6135,
    lng: -122.3455,
    address: '2222 2nd Ave, Seattle, WA',
    neighborhood: 'Belltown',
    categoryKey: 'nightclub',
    pulseScore: 80,
    dressCode: 'smart_casual',
    coverChargeCents: 1500,
    priceRange: 2,
    hours: { ...nightlifeHours },
  }),
  curated({
    id: 'sea-lava-lounge',
    name: 'Lava Lounge',
    lat: 47.6139,
    lng: -122.3458,
    address: '2226 2nd Ave, Seattle, WA',
    neighborhood: 'Belltown',
    categoryKey: 'lounge',
    pulseScore: 55,
    dressCode: 'casual',
    coverChargeCents: 0,
    priceRange: 2,
    hours: {
      monday: '4:00 PM - 2:00 AM',
      tuesday: '4:00 PM - 2:00 AM',
      wednesday: '4:00 PM - 2:00 AM',
      thursday: '4:00 PM - 2:00 AM',
      friday: '4:00 PM - 2:00 AM',
      saturday: '4:00 PM - 2:00 AM',
      sunday: '4:00 PM - 2:00 AM',
    },
  }),
  curated({
    id: 'sea-tula',
    name: "Tula's Restaurant & Jazz Club",
    lat: 47.6148,
    lng: -122.3442,
    address: '2214 2nd Ave, Seattle, WA',
    neighborhood: 'Belltown',
    categoryKey: 'music_venue',
    pulseScore: 58,
    dressCode: 'smart_casual',
    coverChargeCents: 1000,
    priceRange: 3,
    hours: {
      wednesday: '7:00 PM - 12:00 AM',
      thursday: '7:00 PM - 12:00 AM',
      friday: '7:00 PM - 1:00 AM',
      saturday: '7:00 PM - 1:00 AM',
    },
  }),
  curated({
    id: 'sea-shortys',
    name: "Shorty's",
    lat: 47.6132,
    lng: -122.3451,
    address: '2222 2nd Ave, Seattle, WA',
    neighborhood: 'Belltown',
    categoryKey: 'bar',
    pulseScore: 62,
    dressCode: 'casual',
    coverChargeCents: 0,
    priceRange: 1,
    hours: {
      monday: '12:00 PM - 2:00 AM',
      tuesday: '12:00 PM - 2:00 AM',
      wednesday: '12:00 PM - 2:00 AM',
      thursday: '12:00 PM - 2:00 AM',
      friday: '12:00 PM - 2:00 AM',
      saturday: '12:00 PM - 2:00 AM',
      sunday: '12:00 PM - 2:00 AM',
    },
  }),
  curated({
    id: 'sea-tractor',
    name: 'Tractor Tavern',
    lat: 47.6651,
    lng: -122.3841,
    address: '5213 Ballard Ave NW, Seattle, WA',
    neighborhood: 'Ballard',
    categoryKey: 'music_venue',
    pulseScore: 66,
    phone: '(206) 789-3599',
    website: 'https://tractortavern.com',
    dressCode: 'casual',
    coverChargeCents: 1500,
    priceRange: 2,
    hours: { ...musicHours },
  }),
  curated({
    id: 'sea-sunset',
    name: 'The Sunset Tavern',
    lat: 47.6667,
    lng: -122.3841,
    address: '5433 Ballard Ave NW, Seattle, WA',
    neighborhood: 'Ballard',
    categoryKey: 'music_venue',
    pulseScore: 60,
    dressCode: 'casual',
    coverChargeCents: 1200,
    priceRange: 2,
    hours: { ...musicHours },
  }),
  curated({
    id: 'sea-ballard-smoke',
    name: 'Ballard Smoke Shop',
    lat: 47.6685,
    lng: -122.3848,
    address: '5439 Ballard Ave NW, Seattle, WA',
    neighborhood: 'Ballard',
    categoryKey: 'bar',
    pulseScore: 48,
    dressCode: 'casual',
    coverChargeCents: 0,
    priceRange: 1,
    hours: {
      monday: '11:00 AM - 2:00 AM',
      tuesday: '11:00 AM - 2:00 AM',
      wednesday: '11:00 AM - 2:00 AM',
      thursday: '11:00 AM - 2:00 AM',
      friday: '11:00 AM - 2:00 AM',
      saturday: '11:00 AM - 2:00 AM',
      sunday: '11:00 AM - 2:00 AM',
    },
  }),
  curated({
    id: 'sea-kings',
    name: "King's Hardware",
    lat: 47.6689,
    lng: -122.3835,
    address: '5225 Ballard Ave NW, Seattle, WA',
    neighborhood: 'Ballard',
    categoryKey: 'bar',
    pulseScore: 52,
    dressCode: 'casual',
    coverChargeCents: 0,
    priceRange: 2,
    hours: {
      monday: '4:00 PM - 2:00 AM',
      tuesday: '4:00 PM - 2:00 AM',
      wednesday: '4:00 PM - 2:00 AM',
      thursday: '4:00 PM - 2:00 AM',
      friday: '4:00 PM - 2:00 AM',
      saturday: '12:00 PM - 2:00 AM',
      sunday: '12:00 PM - 2:00 AM',
    },
  }),
  curated({
    id: 'sea-stoup',
    name: 'Stoup Brewing',
    lat: 47.6658,
    lng: -122.3732,
    address: '1108 NW 52nd St, Seattle, WA',
    neighborhood: 'Ballard',
    categoryKey: 'brewery',
    pulseScore: 54,
    website: 'https://stoupbrewing.com',
    dressCode: 'casual',
    coverChargeCents: 0,
    priceRange: 2,
    indoorOutdoor: 'both',
    hours: {
      monday: '12:00 PM - 10:00 PM',
      tuesday: '12:00 PM - 10:00 PM',
      wednesday: '12:00 PM - 10:00 PM',
      thursday: '12:00 PM - 10:00 PM',
      friday: '12:00 PM - 11:00 PM',
      saturday: '12:00 PM - 11:00 PM',
      sunday: '12:00 PM - 9:00 PM',
    },
  }),
  curated({
    id: 'sea-fremont-brewing',
    name: 'Fremont Brewing',
    lat: 47.6492,
    lng: -122.3498,
    address: '1050 N 34th St, Seattle, WA',
    neighborhood: 'Fremont',
    categoryKey: 'brewery',
    pulseScore: 58,
    phone: '(206) 420-2407',
    website: 'https://fremontbrewing.com',
    dressCode: 'casual',
    coverChargeCents: 0,
    priceRange: 2,
    indoorOutdoor: 'both',
    hours: {
      monday: '11:00 AM - 9:00 PM',
      tuesday: '11:00 AM - 9:00 PM',
      wednesday: '11:00 AM - 9:00 PM',
      thursday: '11:00 AM - 9:00 PM',
      friday: '11:00 AM - 10:00 PM',
      saturday: '11:00 AM - 10:00 PM',
      sunday: '11:00 AM - 9:00 PM',
    },
  }),
  curated({
    id: 'sea-brouwer',
    name: "Brouwer's Cafe",
    lat: 47.6495,
    lng: -122.3505,
    address: '400 N 36th St, Seattle, WA',
    neighborhood: 'Fremont',
    categoryKey: 'bar',
    pulseScore: 56,
    dressCode: 'casual',
    coverChargeCents: 0,
    priceRange: 2,
    hours: {
      monday: '11:00 AM - 2:00 AM',
      tuesday: '11:00 AM - 2:00 AM',
      wednesday: '11:00 AM - 2:00 AM',
      thursday: '11:00 AM - 2:00 AM',
      friday: '11:00 AM - 2:00 AM',
      saturday: '11:00 AM - 2:00 AM',
      sunday: '11:00 AM - 2:00 AM',
    },
  }),
  curated({
    id: 'sea-high-dive',
    name: 'The High Dive',
    lat: 47.6615,
    lng: -122.3502,
    address: '513 N 36th St, Seattle, WA',
    neighborhood: 'Fremont',
    categoryKey: 'music_venue',
    pulseScore: 50,
    dressCode: 'casual',
    coverChargeCents: 1000,
    priceRange: 1,
    hours: { ...musicHours },
  }),
  curated({
    id: 'sea-showbox',
    name: 'The Showbox',
    lat: 47.6088,
    lng: -122.3371,
    address: '1426 1st Ave, Seattle, WA',
    neighborhood: 'Downtown',
    categoryKey: 'music_venue',
    pulseScore: 81,
    phone: '(206) 628-3151',
    website: 'https://showboxpresents.com',
    dressCode: 'casual',
    coverChargeCents: 3000,
    coverChargeNote: 'Ticketed events',
    priceRange: 2,
    hours: { ...musicHours, sunday: '7:00 PM - 2:00 AM' },
  }),
  curated({
    id: 'sea-foundation',
    name: 'Foundation Nightclub',
    lat: 47.5981,
    lng: -122.3293,
    address: '2218 Western Ave, Seattle, WA',
    neighborhood: 'Downtown',
    categoryKey: 'nightclub',
    pulseScore: 88,
    phone: '(206) 223-0480',
    website: 'https://foundationnightclub.com',
    dressCode: 'upscale',
    coverChargeCents: 2500,
    priceRange: 3,
    hours: {
      thursday: '10:00 PM - 3:00 AM',
      friday: '10:00 PM - 4:00 AM',
      saturday: '10:00 PM - 4:00 AM',
    },
  }),
  curated({
    id: 'sea-triple-door',
    name: 'The Triple Door',
    lat: 47.6064,
    lng: -122.3334,
    address: '216 Union St, Seattle, WA',
    neighborhood: 'Downtown',
    categoryKey: 'music_venue',
    pulseScore: 58,
    dressCode: 'smart_casual',
    coverChargeCents: 2000,
    priceRange: 3,
    hours: {
      tuesday: '5:00 PM - 11:00 PM',
      wednesday: '5:00 PM - 11:00 PM',
      thursday: '5:00 PM - 12:00 AM',
      friday: '5:00 PM - 1:00 AM',
      saturday: '5:00 PM - 1:00 AM',
    },
  }),
  curated({
    id: 'sea-owl-n-thistle',
    name: 'Owl N Thistle',
    lat: 47.6035,
    lng: -122.3338,
    address: '808 Post Ave, Seattle, WA',
    neighborhood: 'Downtown',
    categoryKey: 'bar',
    pulseScore: 45,
    dressCode: 'casual',
    coverChargeCents: 0,
    priceRange: 2,
    hours: {
      monday: '11:30 AM - 2:00 AM',
      tuesday: '11:30 AM - 2:00 AM',
      wednesday: '11:30 AM - 2:00 AM',
      thursday: '11:30 AM - 2:00 AM',
      friday: '11:30 AM - 2:00 AM',
      saturday: '11:30 AM - 2:00 AM',
      sunday: '11:30 AM - 2:00 AM',
    },
  }),
  curated({
    id: 'sea-pink-door',
    name: 'The Pink Door',
    lat: 47.6089,
    lng: -122.3405,
    address: '1919 Post Alley, Seattle, WA',
    neighborhood: 'Downtown',
    categoryKey: 'restaurant',
    pulseScore: 62,
    phone: '(206) 443-3241',
    website: 'https://thepinkdoor.net',
    dressCode: 'smart_casual',
    coverChargeCents: 0,
    priceRange: 3,
    hours: {
      tuesday: '4:30 PM - 10:00 PM',
      wednesday: '4:30 PM - 10:00 PM',
      thursday: '4:30 PM - 10:00 PM',
      friday: '4:30 PM - 11:00 PM',
      saturday: '4:30 PM - 11:00 PM',
      sunday: '4:30 PM - 10:00 PM',
    },
  }),
  curated({
    id: 'sea-zig-zag',
    name: 'Zig Zag Café',
    lat: 47.6082,
    lng: -122.3412,
    address: '1501 Western Ave, Seattle, WA',
    neighborhood: 'Downtown',
    categoryKey: 'cocktail_bar',
    pulseScore: 68,
    dressCode: 'smart_casual',
    coverChargeCents: 0,
    priceRange: 3,
    hours: {
      monday: '5:00 PM - 1:00 AM',
      tuesday: '5:00 PM - 1:00 AM',
      wednesday: '5:00 PM - 1:00 AM',
      thursday: '5:00 PM - 1:00 AM',
      friday: '5:00 PM - 2:00 AM',
      saturday: '5:00 PM - 2:00 AM',
      sunday: '5:00 PM - 1:00 AM',
    },
  }),
  curated({
    id: 'sea-monkey-loft',
    name: 'Monkey Loft',
    lat: 47.5788,
    lng: -122.3345,
    address: '2915 1st Ave S, Seattle, WA',
    neighborhood: 'SODO',
    categoryKey: 'nightclub',
    pulseScore: 76,
    dressCode: 'casual',
    coverChargeCents: 1500,
    priceRange: 2,
    hours: { ...nightlifeHours },
  }),
  curated({
    id: 'sea-chop-suey',
    name: 'Chop Suey',
    lat: 47.6139,
    lng: -122.3135,
    address: '1325 E Madison St, Seattle, WA',
    neighborhood: 'Capitol Hill',
    categoryKey: 'music_venue',
    pulseScore: 64,
    dressCode: 'casual',
    coverChargeCents: 1500,
    priceRange: 2,
    hours: { ...musicHours },
  }),
  curated({
    id: 'sea-lincoln',
    name: 'Lincoln',
    lat: 47.6205,
    lng: -122.3128,
    address: '801 E Thomas St, Seattle, WA',
    neighborhood: 'Capitol Hill',
    categoryKey: 'bar',
    pulseScore: 57,
    dressCode: 'casual',
    coverChargeCents: 0,
    priceRange: 2,
    hours: {
      monday: '4:00 PM - 2:00 AM',
      tuesday: '4:00 PM - 2:00 AM',
      wednesday: '4:00 PM - 2:00 AM',
      thursday: '4:00 PM - 2:00 AM',
      friday: '4:00 PM - 2:00 AM',
      saturday: '12:00 PM - 2:00 AM',
      sunday: '12:00 PM - 2:00 AM',
    },
  }),
  curated({
    id: 'sea-optimism',
    name: 'Optimism Brewing',
    lat: 47.6148,
    lng: -122.3175,
    address: '1158 Broadway, Seattle, WA',
    neighborhood: 'Capitol Hill',
    categoryKey: 'brewery',
    pulseScore: 53,
    website: 'https://optimismbrewing.com',
    dressCode: 'casual',
    coverChargeCents: 0,
    priceRange: 2,
    indoorOutdoor: 'both',
    hours: {
      monday: '12:00 PM - 10:00 PM',
      tuesday: '12:00 PM - 10:00 PM',
      wednesday: '12:00 PM - 10:00 PM',
      thursday: '12:00 PM - 11:00 PM',
      friday: '12:00 PM - 12:00 AM',
      saturday: '12:00 PM - 12:00 AM',
      sunday: '12:00 PM - 10:00 PM',
    },
  }),
  curated({
    id: 'sea-bathtub-gin',
    name: 'Bathtub Gin & Co.',
    lat: 47.6136,
    lng: -122.3456,
    address: '2207 2nd Ave, Seattle, WA',
    neighborhood: 'Belltown',
    categoryKey: 'cocktail_bar',
    pulseScore: 71,
    dressCode: 'smart_casual',
    coverChargeCents: 0,
    priceRange: 3,
    hours: {
      monday: '5:00 PM - 1:00 AM',
      tuesday: '5:00 PM - 1:00 AM',
      wednesday: '5:00 PM - 1:00 AM',
      thursday: '5:00 PM - 1:00 AM',
      friday: '5:00 PM - 2:00 AM',
      saturday: '5:00 PM - 2:00 AM',
      sunday: '5:00 PM - 1:00 AM',
    },
  }),
  curated({
    id: 'sea-noble-fir',
    name: 'The Noble Fir',
    lat: 47.6018,
    lng: -122.3345,
    address: '531 1st Ave S, Seattle, WA',
    neighborhood: 'Pioneer Square',
    categoryKey: 'bar',
    pulseScore: 49,
    dressCode: 'casual',
    coverChargeCents: 0,
    priceRange: 2,
    hours: {
      monday: '4:00 PM - 12:00 AM',
      tuesday: '4:00 PM - 12:00 AM',
      wednesday: '4:00 PM - 12:00 AM',
      thursday: '4:00 PM - 1:00 AM',
      friday: '4:00 PM - 2:00 AM',
      saturday: '2:00 PM - 2:00 AM',
      sunday: '2:00 PM - 12:00 AM',
    },
  }),
]

export const SEATTLE_CURATED_NEIGHBORHOODS = [
  'Capitol Hill',
  'Belltown',
  'Ballard',
  'Fremont',
  'Downtown',
  'SODO',
  'Pioneer Square',
] as const

export function getSeattleCuratedByNeighborhood(neighborhood: string): Venue[] {
  return SEATTLE_NIGHTLIFE_CURATED.filter(
    (v) => v.neighborhood?.toLowerCase() === neighborhood.toLowerCase(),
  )
}
