import type { Venue } from '../types'

/** Curated Seattle beta inventory — PRD §3.1 (30 venues, 5 neighborhoods). */
export const SEATTLE_LAUNCH_NEIGHBORHOODS: Record<string, string> = {
  'venue-1': 'Capitol Hill',
  'venue-3': 'Capitol Hill',
  'venue-4': 'Capitol Hill',
  'venue-13': 'Capitol Hill',
  'venue-22': 'Capitol Hill',
  'venue-12': 'Capitol Hill',
  'venue-19': 'Capitol Hill',
  'venue-17': 'Capitol Hill',
  'venue-2': 'Belltown',
  'venue-6': 'Belltown',
  'venue-7': 'Belltown',
  'venue-8': 'Belltown',
  'venue-14': 'Belltown',
  'venue-23': 'Belltown',
  'venue-27': 'Belltown',
  'venue-30': 'Belltown',
  'venue-10': 'Ballard',
  'venue-11': 'Ballard',
  'venue-16': 'Fremont',
  'venue-31': 'Fremont',
  'venue-34': 'Fremont',
  'venue-36': 'Fremont',
  'venue-35': 'Fremont',
  'venue-38': 'Fremont',
  'venue-18': 'Downtown',
  'venue-29': 'Downtown',
  'venue-21': 'Downtown',
  'venue-28': 'Seattle',
  'venue-49': 'Seattle',
  'venue-5': 'Seattle',
}

export const SEATTLE_LAUNCH_VENUE_IDS = [
  'venue-1',
  'venue-3',
  'venue-4',
  'venue-13',
  'venue-22',
  'venue-12',
  'venue-19',
  'venue-17',
  'venue-2',
  'venue-6',
  'venue-7',
  'venue-8',
  'venue-14',
  'venue-23',
  'venue-27',
  'venue-30',
  'venue-10',
  'venue-11',
  'venue-16',
  'venue-31',
  'venue-34',
  'venue-36',
  'venue-35',
  'venue-38',
  'venue-18',
  'venue-29',
  'venue-21',
  'venue-28',
  'venue-49',
  'venue-5',
] as const

export const SEATTLE_LAUNCH_VENUES: Venue[] = [
  {
    id: 'venue-1',
    name: "Neumos",
    location: { lat: 47.6145, lng: -122.3205, address: "925 E Pike St, Seattle, WA" },
    city: 'Seattle',
    state: 'WA',
    category: "Music Venue",
    pulseScore: 85,
    seeded: true,
  },
  {
    id: 'venue-3',
    name: "Q Nightclub",
    location: { lat: 47.6138, lng: -122.3198, address: "1426 Broadway, Seattle, WA" },
    city: 'Seattle',
    state: 'WA',
    category: "Nightclub",
    pulseScore: 92,
    seeded: true,
  },
  {
    id: 'venue-4',
    name: "Kremwerk",
    location: { lat: 47.6154, lng: -122.3213, address: "1809 Minor Ave, Seattle, WA" },
    city: 'Seattle',
    state: 'WA',
    category: "Nightclub",
    pulseScore: 68,
    seeded: true,
  },
  {
    id: 'venue-13',
    name: "The Unicorn",
    location: { lat: 47.6142, lng: -122.3196, address: "1118 E Pike St, Seattle, WA" },
    city: 'Seattle',
    state: 'WA',
    category: "Bar",
    pulseScore: 76,
    seeded: true,
  },
  {
    id: 'venue-22',
    name: "The Comet Tavern",
    location: { lat: 47.6142, lng: -122.3181, address: "922 E Pike St, Seattle, WA" },
    city: 'Seattle',
    state: 'WA',
    category: "Bar",
    pulseScore: 0,
    seeded: true,
  },
  {
    id: 'venue-12',
    name: "Barboza",
    location: { lat: 47.6145, lng: -122.3207, address: "925 E Pike St, Seattle, WA" },
    city: 'Seattle',
    state: 'WA',
    category: "Lounge",
    pulseScore: 64,
    seeded: true,
  },
  {
    id: 'venue-19',
    name: "Chop Suey",
    location: { lat: 47.6145, lng: -122.3194, address: "1325 E Madison St, Seattle, WA" },
    city: 'Seattle',
    state: 'WA',
    category: "Music Venue",
    pulseScore: 0,
    seeded: true,
  },
  {
    id: 'venue-17',
    name: "Re-bar",
    location: { lat: 47.6152, lng: -122.3202, address: "1114 Howell St, Seattle, WA" },
    city: 'Seattle',
    state: 'WA',
    category: "nightlife",
    pulseScore: 15,
    seeded: true,
  },
  {
    id: 'venue-2',
    name: "The Crocodile",
    location: { lat: 47.6162, lng: -122.3488, address: "2200 2nd Ave, Seattle, WA" },
    city: 'Seattle',
    state: 'WA',
    category: "Music Venue",
    pulseScore: 72,
    seeded: true,
  },
  {
    id: 'venue-6',
    name: "The Showbox",
    location: { lat: 47.6088, lng: -122.3371, address: "1426 1st Ave, Seattle, WA" },
    city: 'Seattle',
    state: 'WA',
    category: "Music Venue",
    pulseScore: 81,
    seeded: true,
  },
  {
    id: 'venue-7',
    name: "The Triple Door",
    location: { lat: 47.6064, lng: -122.3334, address: "216 Union St, Seattle, WA" },
    city: 'Seattle',
    state: 'WA',
    category: "Music Venue",
    pulseScore: 58,
    seeded: true,
  },
  {
    id: 'venue-8',
    name: "Foundation Nightclub",
    location: { lat: 47.5981, lng: -122.3293, address: "2218 Western Ave, Seattle, WA" },
    city: 'Seattle',
    state: 'WA',
    category: "Nightclub",
    pulseScore: 88,
    seeded: true,
  },
  {
    id: 'venue-14',
    name: "Monkey Loft",
    location: { lat: 47.5981, lng: -122.3311, address: "2915 1st Ave, Seattle, WA" },
    city: 'Seattle',
    state: 'WA',
    category: "Dance Club",
    pulseScore: 0,
    seeded: true,
  },
  {
    id: 'venue-23',
    name: "Ora Seattle",
    location: { lat: 47.6163, lng: -122.3487, address: "2208 1st Ave, Seattle, WA" },
    city: 'Seattle',
    state: 'WA',
    category: "nightlife",
    pulseScore: 20,
    seeded: true,
  },
  {
    id: 'venue-27',
    name: "Lava Lounge",
    location: { lat: 47.6599, lng: -122.3843, address: "2226 2nd Ave, Seattle, WA" },
    city: 'Seattle',
    state: 'WA',
    category: "Lounge",
    pulseScore: 0,
    seeded: true,
  },
  {
    id: 'venue-30',
    name: "The Moore Theatre",
    location: { lat: 47.6106, lng: -122.3378, address: "1932 2nd Ave, Seattle, WA" },
    city: 'Seattle',
    state: 'WA',
    category: "Music Venue",
    pulseScore: 0,
    seeded: true,
  },
  {
    id: 'venue-10',
    name: "Tractor Tavern",
    location: { lat: 47.6651, lng: -122.3841, address: "5213 Ballard Ave NW, Seattle, WA" },
    city: 'Seattle',
    state: 'WA',
    category: "Music Venue",
    pulseScore: 45,
    seeded: true,
  },
  {
    id: 'venue-11',
    name: "The Sunset Tavern",
    location: { lat: 47.6667, lng: -122.3841, address: "5433 Ballard Ave NW, Seattle, WA" },
    city: 'Seattle',
    state: 'WA',
    category: "Bar",
    pulseScore: 0,
    seeded: true,
  },
  {
    id: 'venue-16',
    name: "Nectar Lounge",
    location: { lat: 47.6709, lng: -122.3167, address: "412 N 36th St, Seattle, WA" },
    city: 'Seattle',
    state: 'WA',
    category: "Music Venue",
    pulseScore: 38,
    seeded: true,
  },
  {
    id: 'venue-31',
    name: "The George & Dragon Pub",
    location: { lat: 47.6497, lng: -122.3499, address: "206 N 36th St, Seattle, WA" },
    city: 'Seattle',
    state: 'WA',
    category: "Bar",
    pulseScore: 52,
    seeded: true,
  },
  {
    id: 'venue-34',
    name: "Fremont Brewing",
    location: { lat: 47.6514, lng: -122.3541, address: "1050 N 34th St, Seattle, WA" },
    city: 'Seattle',
    state: 'WA',
    category: "Brewery",
    pulseScore: 45,
    seeded: true,
  },
  {
    id: 'venue-36',
    name: "Fremont Abbey Arts Center",
    location: { lat: 47.6515, lng: -122.3518, address: "4272 Fremont Ave N, Seattle, WA" },
    city: 'Seattle',
    state: 'WA',
    category: "Music Venue",
    pulseScore: 0,
    seeded: true,
  },
  {
    id: 'venue-35',
    name: "The Barrel Thief",
    location: { lat: 47.6493, lng: -122.3492, address: "3417 Evanston Ave N, Seattle, WA" },
    city: 'Seattle',
    state: 'WA',
    category: "Bar",
    pulseScore: 0,
    seeded: true,
  },
  {
    id: 'venue-38',
    name: "Milstead & Co",
    location: { lat: 47.6494, lng: -122.3491, address: "770 N 34th St, Seattle, WA" },
    city: 'Seattle',
    state: 'WA',
    category: "Café",
    pulseScore: 0,
    seeded: true,
  },
  {
    id: 'venue-18',
    name: "The 5 Point Cafe",
    location: { lat: 47.6205, lng: -122.3473, address: "415 Cedar St, Seattle, WA" },
    city: 'Seattle',
    state: 'WA',
    category: "Bar",
    pulseScore: 0,
    seeded: true,
  },
  {
    id: 'venue-29',
    name: "The Paramount Theatre",
    location: { lat: 47.6125, lng: -122.3317, address: "911 Pine St, Seattle, WA" },
    city: 'Seattle',
    state: 'WA',
    category: "Music Venue",
    pulseScore: 0,
    seeded: true,
  },
  {
    id: 'venue-21',
    name: "Dimitriou\\",
    location: { lat: 47.6118, lng: -122.3401, address: "2033 6th Ave, Seattle, WA" },
    city: 'Seattle',
    state: 'WA',
    category: "music",
    pulseScore: 18,
    seeded: true,
  },
  {
    id: 'venue-28',
    name: "El Corazon",
    location: { lat: 47.6183, lng: -122.3302, address: "109 Eastlake Ave E, Seattle, WA" },
    city: 'Seattle',
    state: 'WA',
    category: "Music Venue",
    pulseScore: 0,
    seeded: true,
  },
  {
    id: 'venue-49',
    name: "Starbucks Reserve Roastery",
    location: { lat: 47.6274, lng: -122.3366, address: "1124 Pike St, Seattle, WA" },
    city: 'Seattle',
    state: 'WA',
    category: "Café",
    pulseScore: 42,
    seeded: true,
  },
  {
    id: 'venue-5',
    name: "Cafe Racer",
    location: { lat: 47.6698, lng: -122.3214, address: "5828 Roosevelt Way NE, Seattle, WA" },
    city: 'Seattle',
    state: 'WA',
    category: "Café",
    pulseScore: 0,
    seeded: true,
  },
]

export function getSeattleNeighborhood(venueId: string): string | undefined {
  return SEATTLE_LAUNCH_NEIGHBORHOODS[venueId]
}
